// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dovomvvueezhpxultjdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvdm9tdnZ1ZWV6aHB4dWx0amRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NjgwOTAsImV4cCI6MjA1OTU0NDA5MH0.9p6twIOanXc6-nz9DPjLFI0JgJhr__lOtpvnQVIAJxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);